export enum ERoles {
  PRODUCER_ADVISER = 'PRODUCER_ADVISER',
  PRODUCER_ADVISER_ENCOURAGED = 'PRODUCER_ADVISER_ENCOURAGED',
  PRODUCER = 'PRODUCER',
  PROVIDER = 'PROVIDER',
  MARKETER = 'MARKETER',
  CAM = 'KAM',
  KAM = 'KAM',
  CONTACT_REPRESENTATIVE = 'CONTACT_REPRESENTATIVE',
  VERIFIER = 'VERIFIER',
  ADVISER = 'ADVISER',
  TECHNICAL_ADVISER = 'TECHNICAL_ADVISER'
}

export enum TypeRolEnum {
  UCROPIT = 'UCROPIT'
}
